id: f3837a41f9ec490596bdff3e01a42473
initial_creation_type: ocr
source_metadata:
  volumes:
    8ec2f8a7c4fb4979a14440f3064b214b:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: དུག་ལྔ་སྦས་པའི་ལམ་མཆོག་ཏུ་གསང་བ་བསམ་གྱིས་མི་ཁྱབ་པ།
      total_pages: 1953
      volume_number: 27
